# Generated by Django 5.2.14 on 2026-06-02 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ej: TMEC, TLCUEM, CPTPP', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('member_countries', models.JSONField(default=list, help_text='Ej: ["MX", "US", "CA"]', verbose_name='Países miembro (ISO-2)')),
                ('rvc_transaction_threshold', models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='Umbral VCR — valor de transacción (%)')),
                ('rvc_net_cost_threshold', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Umbral VCR — costo neto (%)')),
                ('de_minimis_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='De minimis (%)')),
                ('in_force_from', models.DateField(blank=True, null=True, verbose_name='En vigor desde')),
            ],
            options={
                'verbose_name': 'Tratado (TLC)',
                'verbose_name_plural': 'Tratados (TLC)',
            },
        ),
        migrations.CreateModel(
            name='OriginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hs_pattern', models.CharField(help_text="Prefijo HS al que aplica. Ej: '87', '8703', '870321'", max_length=10, verbose_name='Patrón HS')),
                ('rule_type', models.CharField(choices=[('WO', 'Totalmente obtenido'), ('CTC', 'Salto arancelario'), ('RVC', 'Valor de contenido regional'), ('CTC_OR_RVC', 'Salto arancelario O VCR'), ('CTC_AND_RVC', 'Salto arancelario Y VCR')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Ej: {"shift_level": "CTH", "rvc_method": "transaction", "rvc_threshold": 60, "de_minimis": 10}', verbose_name='Parámetros del motor')),
                ('description', models.TextField(blank=True, verbose_name='Texto de la regla')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Regla de origen',
                'verbose_name_plural': 'Reglas de origen',
            },
        ),
    ]
