# Generated by Django 5.2.14 on 2026-06-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treaties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originrule',
            options={'ordering': ['treaty', 'hs_pattern'], 'verbose_name': 'Regla de origen', 'verbose_name_plural': 'Reglas de origen'},
        ),
        migrations.AlterUniqueTogether(
            name='originrule',
            unique_together={('treaty', 'hs_pattern')},
        ),
    ]
