# Generated by Django 5.2.14 on 2026-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treaties', '0002_alter_originrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originrule',
            name='hs_from',
            field=models.CharField(blank=True, max_length=12, verbose_name='HS desde'),
        ),
        migrations.AddField(
            model_name='originrule',
            name='hs_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nivel HS (2/4/6/8)'),
        ),
        migrations.AddField(
            model_name='originrule',
            name='hs_to',
            field=models.CharField(blank=True, max_length=12, verbose_name='HS hasta'),
        ),
        migrations.AddIndex(
            model_name='originrule',
            index=models.Index(fields=['treaty', 'hs_pattern'], name='treaties_or_treaty__43672f_idx'),
        ),
    ]
