# Generated by Django 5.2.14 on 2026-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treaties', '0003_originrule_hs_from_originrule_hs_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originrule',
            name='hs_pattern',
            field=models.CharField(help_text="Prefijo HS o rango 'desde-hasta' al que aplica. Ej: '87', '8703', '870321', '850110-850164'", max_length=20, verbose_name='Patrón HS'),
        ),
    ]
