# Generated by Django 5.2.14 on 2026-06-02 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
        ('treaties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(max_length=40, verbose_name='Folio')),
                ('certifier_type', models.CharField(choices=[('exporter', 'Exportador'), ('producer', 'Productor'), ('importer', 'Importador')], max_length=20, verbose_name='Tipo de certificador')),
                ('certifier_data', models.JSONField(default=dict, verbose_name='Datos del certificador')),
                ('exporter_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del exportador')),
                ('producer_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del productor')),
                ('importer_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del importador')),
                ('blanket_from', models.DateField(blank=True, null=True, verbose_name='Periodo (desde)')),
                ('blanket_to', models.DateField(blank=True, null=True, verbose_name='Periodo (hasta)')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido el')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Certificado de origen',
                'verbose_name_plural': 'Certificados de origen',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='expedientes/%Y/%m/', verbose_name='Archivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='origin.certificate')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Documento de expediente',
                'verbose_name_plural': 'Documentos de expediente',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUALIFIES', 'Califica'), ('DOES_NOT', 'No califica'), ('INSUFFICIENT', 'Datos insuficientes')], max_length=20)),
                ('criterion', models.CharField(blank=True, max_length=20, verbose_name='Criterio aplicado')),
                ('rvc_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VCR calculado (%)')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Traza del cálculo')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='catalog.product')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treaties.originrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Calificación de origen',
                'verbose_name_plural': 'Calificaciones de origen',
                'unique_together': {('tenant', 'product', 'treaty')},
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='origin.qualification'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('tenant', 'folio')},
        ),
    ]
