# Generated by Django 5.2.14 on 2026-06-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['-computed_at'], 'verbose_name': 'Calificación de origen', 'verbose_name_plural': 'Calificaciones de origen'},
        ),
    ]
