# Generated by Django 5.2.14 on 2026-06-09 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_supplierprofile_country_companyprofile'),
        ('origin', '0002_alter_qualification_options'),
        ('tenants', '0007_usersecurity'),
        ('treaties', '0004_alter_originrule_hs_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomotiveAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_class', models.CharField(choices=[('passenger', 'Automóvil de pasajeros'), ('light_truck', 'Camión ligero'), ('heavy', 'Vehículo pesado'), ('autopart', 'Autoparte (core)')], default='passenger', max_length=20)),
                ('as_of', models.DateField(blank=True, null=True, verbose_name='Fecha de evaluación (phase-in)')),
                ('net_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='Costo neto')),
                ('vnm', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='Valor de materiales no originarios')),
                ('lvc_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='LVC (%)')),
                ('wage_usd_h', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Salario base (USD/h)')),
                ('steel_na_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Acero N.A. (%)')),
                ('aluminum_na_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Aluminio N.A. (%)')),
                ('core_parts_originating', models.BooleanField(default=False, verbose_name='Core parts originarios')),
                ('qualifies', models.BooleanField(default=False, verbose_name='¿Califica (combinado)?')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Traza')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automotive_assessments', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automotive_assessments', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Evaluación automotriz',
                'verbose_name_plural': 'Evaluaciones automotrices',
                'ordering': ['-computed_at'],
                'unique_together': {('tenant', 'product', 'treaty')},
            },
        ),
    ]
