# Generated by Django 5.2.14 on 2026-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_automotiveassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verify_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Token de verificación'),
        ),
    ]
