# Generated by Django 5.2.14 on 2026-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0004_certificate_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='status',
            field=models.CharField(choices=[('QUALIFIES', 'Califica'), ('DOES_NOT', 'No califica'), ('INSUFFICIENT', 'Datos insuficientes'), ('AUTO_REVIEW', 'Requiere régimen automotriz')], max_length=20),
        ),
    ]
