# Generated by Django 5.2.14 on 2026-06-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_purge_noop_price_logs'),
        ('origin', '0006_flag_core_part_qualifications'),
        ('tenants', '0008_license_renewal_amount_license_renewal_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(max_length=40, verbose_name='Folio')),
                ('verify_token', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Token de verificación')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos del certificado')),
                ('sign_method', models.CharField(choices=[('png', 'Firma digital (PNG)'), ('manual', 'Firma manual (escaneada)'), ('qr', 'Firma por QR'), ('png_qr', 'Firma digital + QR'), ('manual_qr', 'Firma manual + QR')], default='png', max_length=12, verbose_name='Método de firma exigido')),
                ('signature_png', models.TextField(blank=True, verbose_name='Firma (PNG base64)')),
                ('scanned_file', models.TextField(blank=True, verbose_name='Escaneado firmado (data URI)')),
                ('signed', models.BooleanField(default=False, verbose_name='Firmado')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Firmado el')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='catalog.solicitationrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Certificado de solicitud',
                'verbose_name_plural': 'Certificados de solicitud',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'folio')},
            },
        ),
    ]
