# Generated by Django 5.2.14 on 2026-06-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_purge_noop_price_logs'),
        ('origin', '0007_solicitationcertificate'),
        ('tenants', '0008_license_renewal_amount_license_renewal_currency_and_more'),
        ('treaties', '0004_alter_originrule_hs_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOriginLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('filename', models.CharField(blank=True, max_length=200, verbose_name='Archivo original')),
                ('file_b64', models.TextField(blank=True, verbose_name='Plantilla (.xlsx en base64)')),
                ('sheet_name', models.CharField(blank=True, max_length=64, verbose_name='Hoja de datos')),
                ('header_row', models.PositiveSmallIntegerField(default=1, verbose_name='Fila de encabezados')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Encabezados detectados')),
                ('mapping', models.JSONField(blank=True, default=dict, verbose_name='Mapeo de columnas')),
                ('client', models.ForeignKey(limit_choices_to={'kind': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='origin_layouts', to='catalog.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_layouts', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Layout de portal de cliente',
                'verbose_name_plural': 'Layouts de portal de cliente',
                'ordering': ['client__name', 'treaty__code'],
                'unique_together': {('tenant', 'client', 'treaty')},
            },
        ),
    ]
