# Generated by Django 5.2.14 on 2026-06-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_companyprofile_logo_png'),
        ('origin', '0008_clientoriginlayout'),
        ('tenants', '0008_license_renewal_amount_license_renewal_currency_and_more'),
        ('treaties', '0004_alter_originrule_hs_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('bom', 'Cálculo por BOM'), ('automotive', 'Evaluación automotriz')], default='bom', max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Resultado')),
                ('criterion', models.CharField(blank=True, max_length=20, verbose_name='Criterio aplicado')),
                ('rvc_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VCR (%)')),
                ('total_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Valor total del BOM')),
                ('vnm', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Valor no originario')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Traza del cálculo')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Análisis de origen (histórico)',
                'verbose_name_plural': 'Análisis de origen (histórico)',
                'ordering': ['-created_at'],
            },
        ),
    ]
