# Generated by Django 5.2.14 on 2026-06-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0009_originanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotiveassessment',
            name='lvc_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='LVC (valor USD)'),
        ),
    ]
