# Generated by Django 5.2.14 on 2026-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0010_automotiveassessment_lvc_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número de factura (envío único)'),
        ),
    ]
