# Generated by Django 5.2.14 on 2026-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_certificate_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='multi_certificates', to='origin.qualification', verbose_name='Partes del documento'),
        ),
    ]
