# Generated by Django 5.2.14 on 2026-08-12 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_party_address'),
        ('origin', '0012_certificate_qualifications'),
        ('tenants', '0008_license_renewal_amount_license_renewal_currency_and_more'),
        ('treaties', '0004_alter_originrule_hs_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('auditor', models.CharField(blank=True, max_length=200, verbose_name='Auditor (cliente/despacho)')),
                ('notified_at', models.DateField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('questionnaire_due', models.DateField(blank=True, null=True, verbose_name='Límite del cuestionario')),
                ('documents_due', models.DateField(blank=True, null=True, verbose_name='Límite de documentos')),
                ('status', models.CharField(choices=[('open', 'En preparación'), ('submitted', 'Entregada'), ('closed', 'Cerrada')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'kind': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='catalog.party')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Auditoría de origen',
                'verbose_name_plural': 'Auditorías de origen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('document', 'Documento requerido'), ('question', 'Pregunta')], default='question', max_length=20)),
                ('section', models.CharField(max_length=120, verbose_name='Sección')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('title', models.TextField(verbose_name='Documento / pregunta')),
                ('provided', models.BooleanField(default=False, verbose_name='Entregado/respondido')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta / comentarios')),
                ('auto_filled', models.BooleanField(default=False, verbose_name='Pre-llenado por la plataforma')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='origin.audit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Renglón de auditoría',
                'verbose_name_plural': 'Renglones de auditoría',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('data_b64', models.TextField(verbose_name='Contenido (base64)')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='origin.audit')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='origin.auditdocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de auditoría',
                'verbose_name_plural': 'Adjuntos de auditoría',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(blank=True, max_length=60, verbose_name='Modelo/plataforma')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='origin.audit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Parte auditada',
                'verbose_name_plural': 'Partes auditadas',
                'unique_together': {('audit', 'product', 'treaty')},
            },
        ),
    ]
