# Generated by Django 5.2.14 on 2026-08-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_party_address'),
        ('origin', '0013_audit_auditdocument_auditfile_audititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='kind',
            field=models.CharField(choices=[('client_audit', 'Un cliente audita a la empresa'), ('supplier_audit', 'La empresa audita a un proveedor')], default='client_audit', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_audits', to='catalog.party'),
        ),
    ]
