# Generated by Django 5.2.14 on 2026-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0014_audit_kind_audit_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=2, verbose_name='Idioma del documento'),
        ),
    ]
