# Generated by Django 5.2.14 on 2026-06-02 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_solicitationrequest'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Solo para usuarios proveedor: la empresa proveedora que representan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.party'),
        ),
    ]
