# Generated by Django 5.2.14 on 2026-06-02 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_membership_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('trial', 'Prueba'), ('basic', 'Básico'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('expired', 'Vencida')], default='active', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máx. usuarios')),
                ('max_products', models.PositiveIntegerField(default=100, verbose_name='Máx. productos')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
    ]
