# Generated by Django 5.2.14 on 2026-06-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Empresa (tenant)', 'verbose_name_plural': 'Empresas (tenants)'},
        ),
    ]
