# Generated by Django 5.2.14 on 2026-06-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Activo cuando tiene una contraseña temporal; se apaga al cambiarla.', verbose_name='Debe cambiar contraseña'),
        ),
    ]
