# Generated by Django 5.2.14 on 2026-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_membership_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='login_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Usuario de acceso'),
        ),
    ]
