# Generated by Django 5.2.14 on 2026-06-03 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_membership_login_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguridad de usuario',
                'verbose_name_plural': 'Seguridad de usuarios',
            },
        ),
    ]
