# Generated by Django 5.2.14 on 2026-06-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='renewal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto de renovación'),
        ),
        migrations.AddField(
            model_name='license',
            name='renewal_currency',
            field=models.CharField(default='MXN', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='license',
            name='renewal_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notas de renovación'),
        ),
    ]
