# Generated by Django 5.2.14 on 2026-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_license_renewal_amount_license_renewal_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Activo cuando tiene una contraseña temporal; se apaga al cambiarla.', verbose_name='Debe cambiar contraseña'),
        ),
    ]
