# Generated by Django 5.2.14 on 2026-08-18 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_usersecurity_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenants', models.ManyToManyField(blank=True, related_name='master_scopes', to='tenants.tenant', verbose_name='Empresas asignadas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_scope', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alcance de master limitado',
                'verbose_name_plural': 'Alcances de masters limitados',
            },
        ),
    ]
