# Generated by Django 5.2.14 on 2026-06-02 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('treaties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('supplier', 'Proveedor'), ('customer', 'Cliente')], max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre / Razón social')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='RFC / Tax ID')),
                ('country', models.CharField(help_text='Ej: MX, US, CN', max_length=2, verbose_name='País (ISO-2)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Proveedor/Cliente',
                'verbose_name_plural': 'Proveedores/Clientes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, verbose_name='SKU / Núm. de parte')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('kind', models.CharField(choices=[('material', 'Material / Insumo'), ('subassembly', 'Subensamble'), ('finished', 'Producto terminado')], default='finished', max_length=20)),
                ('hs_code', models.CharField(help_text='6 a 10 dígitos', max_length=10, verbose_name='Fracción arancelaria (HS)')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Costo unitario')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('country_of_origin', models.CharField(blank=True, max_length=2, verbose_name='País de origen (ISO-2)')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'kind': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='catalog.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Producto / Material',
                'verbose_name_plural': 'Productos / Materiales',
                'unique_together': {('tenant', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14, verbose_name='Cantidad')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='catalog.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_components', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Componente de BOM',
                'verbose_name_plural': 'Componentes de BOM',
            },
        ),
        migrations.CreateModel(
            name='SupplierDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_originating', models.BooleanField(default=False, verbose_name='¿Es originario para el tratado?')),
                ('country_of_origin', models.CharField(blank=True, max_length=2, verbose_name='País de origen (ISO-2)')),
                ('valid_from', models.DateField(verbose_name='Vigente desde')),
                ('valid_to', models.DateField(verbose_name='Vigente hasta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='catalog.product')),
                ('supplier', models.ForeignKey(limit_choices_to={'kind': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='catalog.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Declaración de proveedor',
                'verbose_name_plural': 'Declaraciones de proveedor',
            },
        ),
    ]
