# Generated by Django 5.2.14 on 2026-06-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor/Cliente', 'verbose_name_plural': 'Proveedores/Clientes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku'], 'verbose_name': 'Producto / Material', 'verbose_name_plural': 'Productos / Materiales'},
        ),
    ]
