# Generated by Django 5.2.14 on 2026-06-02 21:40

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_party_options_alter_product_options'),
        ('tenants', '0001_initial'),
        ('treaties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de enviar'), ('sent', 'Enviada al proveedor'), ('responded', 'Respondida'), ('expired', 'Vencida')], default='pending', max_length=20)),
                ('token', models.CharField(default=apps.catalog.models._new_token, editable=False, max_length=64, unique=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitation', to='catalog.supplierdeclaration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='catalog.product')),
                ('supplier', models.ForeignKey(limit_choices_to={'kind': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='catalog.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='treaties.treaty')),
            ],
            options={
                'verbose_name': 'Solicitud a proveedor',
                'verbose_name_plural': 'Solicitudes a proveedor',
                'ordering': ['-created_at'],
            },
        ),
    ]
