# Generated by Django 5.2.14 on 2026-06-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_solicitationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único dentro de la empresa.', max_length=140, verbose_name='Slug'),
        ),
    ]
