# Generated by Django 5.2.14 on 2026-06-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_party_slug'),
        ('tenants', '0004_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('tenant', 'slug')},
        ),
    ]
