# Generated by Django 5.2.14 on 2026-06-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_party_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='code',
            field=models.CharField(blank=True, help_text='Clave que la empresa asigna al proveedor (ej. ST01).', max_length=30, verbose_name='Código de proveedor'),
        ),
    ]
