# Generated by Django 5.2.14 on 2026-06-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_party_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Insumos inactivos no se usan en cálculos ni solicitudes.', verbose_name='Activo'),
        ),
    ]
