# Generated by Django 5.2.14 on 2026-06-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text='6 a 10 dígitos', max_length=10, verbose_name='Fracción arancelaria (HS)'),
        ),
    ]
