# Generated by Django 5.2.14 on 2026-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationrequest',
            name='period_from',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo desde'),
        ),
        migrations.AddField(
            model_name='solicitationrequest',
            name='period_to',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo hasta'),
        ),
        migrations.AddField(
            model_name='solicitationrequest',
            name='period_type',
            field=models.CharField(blank=True, choices=[('month', 'Mensual'), ('semester', 'Semestral'), ('year', 'Anual'), ('custom', 'Personalizado')], max_length=20, verbose_name='Periodo'),
        ),
    ]
