# Generated by Django 5.2.14 on 2026-06-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_solicitationrequest_period_from_and_more'),
        ('tenants', '0007_usersecurity'),
        ('treaties', '0002_alter_originrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationrequest',
            name='bom_analysis',
            field=models.BooleanField(default=False, verbose_name='Análisis por BOM'),
        ),
        migrations.CreateModel(
            name='SolicitationBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitation_boms', to='treaties.originrule')),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='catalog.solicitationrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'BOM de solicitud',
                'verbose_name_plural': 'BOMs de solicitud',
            },
        ),
        migrations.CreateModel(
            name='SolicitationBOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.CharField(max_length=100, verbose_name='Número de parte')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Precio unitario')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Cantidad utilizada')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País de origen (ISO-2)')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.solicitationbom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Línea de BOM de solicitud',
                'verbose_name_plural': 'Líneas de BOM de solicitud',
            },
        ),
    ]
