# Generated by Django 5.2.14 on 2026-06-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_solicitationrequest_bom_analysis_solicitationbom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationbomline',
            name='has_origin_evidence',
            field=models.BooleanField(default=False, help_text='Si no, queda sujeto a auditorías internas.', verbose_name='¿Tiene certificado/evidencia de origen?'),
        ),
    ]
