# Generated by Django 5.2.14 on 2026-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_solicitationbomline_has_origin_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationbom',
            name='computed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Calculado el'),
        ),
        migrations.AddField(
            model_name='solicitationbom',
            name='criterion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Criterio aplicado'),
        ),
        migrations.AddField(
            model_name='solicitationbom',
            name='detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='Traza del cálculo'),
        ),
        migrations.AddField(
            model_name='solicitationbom',
            name='origin_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Resultado de origen'),
        ),
        migrations.AddField(
            model_name='solicitationbom',
            name='rvc_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VCR (%)'),
        ),
        migrations.AddField(
            model_name='solicitationbomline',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Necesaria para evaluar el salto arancelario (CTH).', max_length=10, verbose_name='Fracción arancelaria (HS)'),
        ),
    ]
