# Generated by Django 5.2.14 on 2026-06-03 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_solicitationbom_computed_at_and_more'),
        ('tenants', '0007_usersecurity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hs_suggested',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fracción sugerida por proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_suggestions', to='catalog.party'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_suggestion_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comentario de la sugerencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_suggestion_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], max_length=10),
        ),
        migrations.CreateModel(
            name='HsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_hs', models.CharField(blank=True, max_length=10, verbose_name='Fracción anterior')),
                ('new_hs', models.CharField(blank=True, max_length=10, verbose_name='Fracción nueva')),
                ('suggested_by', models.CharField(blank=True, max_length=255, verbose_name='Sugerida por (proveedor)')),
                ('action', models.CharField(max_length=10, verbose_name='Acción')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Comentario')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_logs', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cambio de fracción',
                'verbose_name_plural': 'Cambios de fracción',
                'ordering': ['-created_at'],
            },
        ),
    ]
