# Generated by Django 5.2.14 on 2026-06-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_solicitationlog'),
        ('treaties', '0002_alter_originrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdeclaration',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='treaties.originrule'),
        ),
        migrations.AddField(
            model_name='supplierdeclaration',
            name='value_non_originating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Valor de materiales no originarios'),
        ),
        migrations.AddField(
            model_name='supplierdeclaration',
            name='value_originating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Valor de materiales originarios'),
        ),
    ]
