# Generated by Django 5.2.14 on 2026-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_supplierdeclaration_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationbom',
            name='net_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Costo neto'),
        ),
        migrations.AddField(
            model_name='solicitationbom',
            name='rvc_method',
            field=models.CharField(choices=[('transaction', 'Valor de transacción'), ('net_cost', 'Costo neto')], default='transaction', max_length=20, verbose_name='Método VCR'),
        ),
    ]
