# Generated by Django 5.2.14 on 2026-06-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_solicitationbom_net_cost_solicitationbom_rvc_method'),
        ('tenants', '0007_usersecurity'),
        ('treaties', '0002_alter_originrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_type', models.CharField(blank=True, max_length=60, verbose_name='Tipo/código a mostrar')),
                ('display_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción a mostrar')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='treaties.originrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Presentación de regla (empresa)',
                'verbose_name_plural': 'Presentaciones de regla (empresa)',
                'unique_together': {('tenant', 'rule')},
            },
        ),
    ]
