# Generated by Django 5.2.14 on 2026-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_ruledisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AlterField(
            model_name='solicitationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de enviar'), ('sent', 'Enviada al proveedor'), ('responded', 'Respondida'), ('accepted', 'Aceptada por cliente'), ('rejected', 'Rechazada por cliente'), ('expired', 'Vencida')], default='pending', max_length=20),
        ),
    ]
