# Generated by Django 5.2.14 on 2026-06-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_solicitationrequest_rejection_reason_and_more'),
        ('tenants', '0007_usersecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Razón social')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='RFC / Tax ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='Estado / Provincia')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País (ISO-2)')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('signatory_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de quien firma')),
                ('signatory_title', models.CharField(blank=True, max_length=120, verbose_name='Cargo de quien firma')),
                ('signature_png', models.TextField(blank=True, verbose_name='Firma (PNG en base64)')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='catalog.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Datos del proveedor',
                'verbose_name_plural': 'Datos del proveedor',
            },
        ),
    ]
