# Generated by Django 5.2.14 on 2026-06-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_supplierprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='manual_country',
            field=models.CharField(blank=True, max_length=2, verbose_name='País de origen (manual, ISO-2)'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='manual_is_originating',
            field=models.BooleanField(default=False, verbose_name='¿Originario? (manual)'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='origin_as_of',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo (fecha) de la declaración'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='origin_mode',
            field=models.CharField(choices=[('supplier', 'Declaración del proveedor'), ('manual', 'Captura manual de la empresa')], default='supplier', max_length=20, verbose_name='Fuente de origen'),
        ),
    ]
