# Generated by Django 5.2.14 on 2026-06-10 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_supplierprofile_country_companyprofile'),
        ('tenants', '0008_license_renewal_amount_license_renewal_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('price', 'Precio'), ('origin', 'País de origen')], max_length=10, verbose_name='Tipo de cambio')),
                ('old_value', models.CharField(blank=True, max_length=60, verbose_name='Valor anterior')),
                ('new_value', models.CharField(blank=True, max_length=60, verbose_name='Valor nuevo')),
                ('old_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Precio anterior')),
                ('new_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Precio nuevo')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='Moneda')),
                ('source', models.CharField(choices=[('manual', 'Edición manual'), ('bulk', 'Carga masiva'), ('supplier', 'Proveedor')], default='manual', max_length=10, verbose_name='Origen del cambio')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cambio de precio/origen',
                'verbose_name_plural': 'Cambios de precio/origen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'kind', '-created_at'], name='catalog_pro_product_b5d412_idx')],
            },
        ),
    ]
