# Generated by Django 5.2.14 on 2026-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_productchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='uom',
            field=models.CharField(blank=True, choices=[('PZ', 'Pieza'), ('UN', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('MG', 'Miligramo'), ('TN', 'Tonelada'), ('LB', 'Libra'), ('OZ', 'Onza'), ('MT', 'Metro'), ('CM', 'Centímetro'), ('MM', 'Milímetro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('FT', 'Pie'), ('IN', 'Pulgada'), ('LT', 'Litro'), ('ML', 'Mililitro'), ('GL', 'Galón'), ('PR', 'Par'), ('JG', 'Juego'), ('KT', 'Kit'), ('CJ', 'Caja'), ('RL', 'Rollo'), ('HJ', 'Hoja')], help_text='Código de 2 caracteres (ej. PZ, KG, MT).', max_length=2, verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='solicitationbomline',
            name='uom',
            field=models.CharField(blank=True, choices=[('PZ', 'Pieza'), ('UN', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('MG', 'Miligramo'), ('TN', 'Tonelada'), ('LB', 'Libra'), ('OZ', 'Onza'), ('MT', 'Metro'), ('CM', 'Centímetro'), ('MM', 'Milímetro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('FT', 'Pie'), ('IN', 'Pulgada'), ('LT', 'Litro'), ('ML', 'Mililitro'), ('GL', 'Galón'), ('PR', 'Par'), ('JG', 'Juego'), ('KT', 'Kit'), ('CJ', 'Caja'), ('RL', 'Rollo'), ('HJ', 'Hoja')], help_text='Código de 2 caracteres (ej. PZ, KG, MT).', max_length=2, verbose_name='Unidad de medida'),
        ),
    ]
