# Generated by Django 5.2.14 on 2026-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_purge_noop_price_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo_png',
            field=models.TextField(blank=True, verbose_name='Logo (PNG en base64)'),
        ),
    ]
