# Generated by Django 5.2.14 on 2026-06-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_companyprofile_logo_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Mano de obra directa + indirectos de fabricación. Suma al costo neto del bien (valor regional originario); sube el VCR.', max_digits=14, verbose_name='Mano de obra y costos de conversión'),
        ),
    ]
