# Generated by Django 5.2.14 on 2026-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_product_conversion_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'customer'}, related_name='purchased_products', to='catalog.party'),
        ),
    ]
