# Generated by Django 5.2.14 on 2026-07-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_product_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='address',
            field=models.CharField(blank=True, help_text='Se imprime en los documentos (ej. Importer del certificado).', max_length=255, verbose_name='Dirección'),
        ),
    ]
