# Generated by Django 5.2.14 on 2026-08-13 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_party_address'),
        ('tenants', '0009_usersecurity_must_change_password'),
        ('treaties', '0004_alter_originrule_hs_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOriginDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('data_b64', models.TextField(verbose_name='Contenido (base64)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.supplierdeclaration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_documents', to='catalog.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_documents', to='catalog.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('treaty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_documents', to='treaties.treaty')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado de origen de insumo',
                'verbose_name_plural': 'Certificados de origen de insumos',
                'ordering': ['-created_at'],
            },
        ),
    ]
