# Generated by Django 5.2.14 on 2026-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_productorigindocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción (inglés)'),
        ),
    ]
