# Generated by Django 5.2.14 on 2026-08-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_product_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_core_part',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parte esencial (core part) T-MEC'),
        ),
    ]
