# Generated by Django 5.2.14 on 2026-08-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_product_is_core_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorigindocument',
            name='doc_type',
            field=models.CharField(choices=[('origin', 'Certificado de origen'), ('mill', 'Certificado de molino')], default='origin', max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='productorigindocument',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año del histórico al que corresponde el certificado. Si se omite, se toma del inicio de vigencia o de la fecha de subida.', null=True, verbose_name='Año del expediente'),
        ),
    ]
